" Jacob Reckhard
" My vimrc file

" Misc {{{
set nocompatible              " be iMproved, required
let g:tex_flavor = "latex"
set number
autocmd BufWritePre * :%s/\s\+$//e

set backupdir=./.backup,.,/tmp
set directory=./.backup,/tmp
" }}}
" Vundle {{{
" set the runtime path to include Vundle and initialize
filetype off                  " required, gets turned on later
set rtp+=~/.vim/bundle/Vundle
call vundle#begin()
" let Vundle manage Vundle, required
" Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required
filetype plugin indent on    " required
" }}}
" Tabs {{{
set tabstop=4           " How large \t characters show up
set expandtab           " Tab keystokes become spaces
set shiftwidth=2        " Indent amount for >>, << and autoindent

set showtabline=1       " Enum for when to show the tab bar at the top
" 0 is never, 1 is when there is more then 1 tabs open, and 2 is always
set laststatus=2        " When should the status line be displayed
set cmdheight=1         " The height of the command bar at the bottom

set hlsearch            " highlight matches when searching
" }}}
" Remapings {{{
noremap <F3> :Autoformat<CR>

" Searching
nnoremap <c-s> :nohlsearch<CR> :write<CR>
inoremap <c-s> <Esc> :nohlsearch<CR> :write<CR>
noremap ;; :%s///g<Left><Left><Left>

noremap <TAB> :bn<CR>
noremap <S-TAB> :bp<CR>
command W w
command Wq wq
command WQ wq
command Q q
inoremap jk <Esc>
" }}}
" Buffers {{{
let g:airline#extensions#tabline#enabled = 1 " show buffers at top
set hidden      " switch buffers when some are unsaved
" }}}
" Themes {{{
syntax on                       " Enable syntax highlighting
colorscheme onedark             " My colour scheme of choice

let g:airline_theme='bubblegum' " Theme for airline statusbar plugin
" }}}

" This last line is so this file autofolds when opening
" vim:foldmethod=marker:foldlevel=0
