" Jacob Reckhard
" My vimrc file

" Misc {{{
set nocompatible              " be iMproved, required
let g:tex_flavor = "latex"
autocmd BufWritePre * :%s/\s\+$//e

set backupdir=./.backup,.,/tmp
set directory=./.backup,/tmp
" }}}
" Plugins {{{
call plug#begin('~/.vim/plugged')

" Visuals
Plug 'vim-airline/vim-airline'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'luochen1990/rainbow'
Plug 'https://github.com/joshdick/onedark.vim.git'
Plug 'vim-airline/vim-airline-themes'

" Functionality
Plug 'albfan/ag.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'neomake/neomake'


" Lang Go
Plug 'fatih/vim-go'

" Lang Javascript
Plug 'ternjs/tern_for_vim'
Plug 'carlitux/deoplete-ternjs'
" npm i -g eslint eslint-plugin-standard eslint-plugin-promise eslint-plugin-node eslint-plugin-json


call plug#end()
" }}}
" Tabs {{{
set tabstop=4           " How large \t characters show up
set expandtab           " Tab keystokes become spaces
set shiftwidth=4        " Indent amount for >>, << and autoindent

set showtabline=1       " Enum for when to show the tab bar at the top
" 0 is never, 1 is when there is more then 1 tabs open, and 2 is always
set laststatus=2        " When should the status line be displayed
set cmdheight=1         " The height of the command bar at the bottom

set hlsearch            " highlight matches when searching
" }}}
" Remappings {{{
" Set leader
nnoremap <SPACE> <Nop>
map <SPACE> <leader>

" Searching {{{
nnoremap <leader>sp :Ag!<SPACE>
nnoremap <leader>ss :AgBuffer!<SPACE>
" }}}
" Split management {{{
nnoremap <leader>wsh :split<CR>
nnoremap <leader>wsv :vsplit<CR>
nnoremap <leader>wn <C-W><C-W>
nnoremap <leader>wiv :resize +5<CR>
nnoremap <leader>wih :vertical resize +5<CR>
nnoremap <leader>wdv :resize -5<CR>
nnoremap <leader>wdh :vertical resize -5<CR>
" }}}
" Buffer managment {{{
noremap <TAB> :bn<CR>
noremap <S-TAB> :bp<CR>
" }}}
" Save and Quit {{{
command W w
command Wq wq
command WQ wq
command Q q
" }}}

inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap jk <Esc>
" }}}
" Buffers {{{
let g:airline#extensions#tabline#enabled = 1 " show buffers at top
set hidden      " switch buffers when some are unsaved
" }}}
" Visual Settings {{{
syntax on                       " Enable syntax highlighting
colorscheme onedark             " My colour scheme of choice

let g:airline_theme='bubblegum' " Theme for airline statusbar plugin
let g:rainbow_active = 1
let g:indent_guides_enable_on_vim_startup = 1

set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set list
set number
" }}}
" Plugin Configs {{{
" Javascript {{{
let g:tern_request_timeout = 1
let g:tern_request_timeout = 6000
let g:tern#command = ['tern']
let g:tern#arguments = ['--persistent']
let g:neomake_javascript_enable_makers = ['eslint']
" }}}
" General {{{
let g:deoplete#enable_at_startup = 1
call neomake#configure#automake('nrwi', 500)
" }}}
" }}}


" This last line is so this file autofolds when opening
" vim:foldmethod=marker:foldlevel=0
