#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
# [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
mkdir -p /tmp/jacob


function setup () {
    export NVM_DIR="$HOME/.nvm"

    # NVM is really slow to load, and I almost never need to change node versions
    # plus, I generally have the latest version installed anyways
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    #alias nvm="echo Check bashrc to reenable nvm"


    # Ocaml's opam
    test -r /home/jacob/.opam/opam-init/init.sh && . /home/jacob/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
    eval `opam config env`

    source ~/.bash_aliases
    source ~/.bash_functions
    source ~/.bash-powerline.sh
    source ~/.git-completion.bash

    export VISUAL="vim" # vim as default text editor
    export TERM=xterm-color
    set -o vi
    bind -x '"\C-a":"fg"' # Easier fg command

    export GUILE_LOAD_PATH="/data/Coding/guile/"
    export GO111MODULE="auto"

    welcome_message
}

setup
