#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source ~/.bash_aliases
source ~/.bash_functions
source ~/.bash-powerline.sh
source ~/.git-completion.bash


export VISUAL="nvim" # vim as default text editor
export TERM=xterm-color
set -o vi
bind -x '"\C-a":"fg"' # Easier fg command
