#
# ~/.bash_profile
#

export PATH="$PATH:~/bin" # Add user bin
export PATH="$PATH:~/.local/bin" # Add user bin
export PATH="$PATH:~/.cargo/bin" # Add cargo bin
export PATH="$PATH:~/go/bin" # Add go bin
export PATH="$PATH:/opt/android-studio/bin" # Add android studio bin
export PATH="$PATH:/opt/dart-sdk/bin" # Add dart bin
export PATH="$PATH:/opt/flutter/bin" # Add flutter bin

export ARDUINO_DIR=''
export ARDMK_DIR='/usr/share/arduino'
export AVR_TOOLS_DIR='/usr/include'


[[ -f ~/.bashrc ]] && . ~/.bashrc
