alias ls="ls -v --color"
alias ranger="source ranger"
alias background="feh --randomize --bg-fill ~/Pictures/wallpapers/*"
alias gitlog="git -c core.pager='less -SRF' log --oneline --graph --decorate"
alias please="sudo zypper"

alias et='emacsclient -create-frame -ta=""'
alias ec='emacsclient -create-frame -ca=""'

alias fin="todo -r"
